stages:
  preparation:
    cmd: python src/preparation.py
    deps:
    - data/raw
    - src/preparation.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/model.joblib
